spring:
  profiles:
    active: local

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: ${MONGO_DATABASE_NAME}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER_NAME}
      password: ${REDIS_BYPASS_PASSWORD}
      ssl:
        enabled: false

  mail:
    host: ${MAIL_HOST}
    port: ${PORT}
    username: ${GMAIL}
    password:  ${GMAIL_BYPASS_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080


  main:
    allow-circular-references: true
